FROM ubuntu:22.04

RUN apt update && apt install -y curl

CMD curl -LsSf https://astral.sh/uv/install.sh | sh
 
CMD cd /code/anomaly-detection-using-soundn

RUN apt update && apt install -y python3 python3-pip && \
    uv pip install torch torchvision --index-url https://download.pytorch.org/whl/cu129
